In [6]:
# 导入模块和包
import numpy as np
import scipy.io as sio
import scipy
import matplotlib.pyplot as plt

%matplotlib inline

In [7]:
# 设置图片位置
image_path = "./images"

# 设置数据位置
data_path = "./dataset/ml-25m/"

# 加载原始评分数据和预测评分数据
user_item_score = sio.mmread(data_path + "user_item_score")
R = scipy.sparse.csc_matrix.todense(user_item_score)

pred_R = sio.mmread(data_path + "pred_R")


In [8]:
# 查看原始评分矩阵
print(R)

# 查看预测评分矩阵
print(pred_R)

[[2.  0.  0.  ... 0.  0.  0. ]
 [0.  5.  0.  ... 0.  0.  0. ]
 [0.  0.  3.5 ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]]
[[3.23409759 3.57396595 2.20319403 ... 3.4952943  2.95463192 3.62277943]
 [2.69861046 3.34606225 1.61229123 ... 3.32577077 2.31390298 2.61656377]
 [3.41951007 3.68362418 2.07386574 ... 3.82444454 2.88866793 3.45153533]
 ...
 [2.60300694 2.71026493 1.42846608 ... 3.01949133 2.03710523 2.49860564]
 [2.58765039 3.20752425 1.65419813 ... 3.02549974 2.35840766 2.53001137]
 [2.61242354 2.95880541 1.50926895 ... 3.11253263 2.00272608 2.72000283]]


In [9]:
R

matrix([[2. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 5. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 3.5, ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0. , 0. ]])